import "dotenv/config";
import mongoose from "mongoose";
import Recipe from "./models/Recipe.js";

const MONGODB_URI =
  process.env.MONGODB_URI || "mongodb://127.0.0.1:27017/recipe-box";
// its full same only from mockrecipes only
const recipes = [
  {
    title: "Creamy Garlic Herb Pasta",
    description:
      "A luscious pasta tossed in a silky garlic and fresh herb sauce, finished with aged parmesan.",
    image: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800",
    ingredients: [
      { name: "Spaghetti", quantity: "400", unit: "g" },
      { name: "Garlic", quantity: "6", unit: "cloves" },
      { name: "Heavy Cream", quantity: "200", unit: "ml" },
      { name: "Parmesan", quantity: "80", unit: "g" },
      { name: "Fresh Basil", quantity: "1", unit: "bunch" },
      { name: "Olive Oil", quantity: "3", unit: "tbsp" },
      { name: "Salt", quantity: "to taste", unit: "" },
    ],
    instructions: [
      "Cook pasta in salted boiling water until al dente.",
      "Sauté minced garlic in olive oil over medium heat until golden.",
      "Add heavy cream and simmer for 3 minutes.",
      "Toss in the drained pasta, parmesan, and fresh herbs.",
      "Season and serve immediately with extra parmesan.",
    ],
    tags: ["Italian", "Comfort Food", "Vegetarian", "Dinner"],
    prepTime: 10,
    cookTime: 20,
    servings: 4,
    difficulty: "Easy",
    authorId: "u1",
    authorName: "Chef Isabella",
    rating: 4.8,
    ratingCount: 124,
    ratingTotal: 595,
    nutritionalInfo: { calories: 520, protein: 18, carbs: 62, fat: 22 },
    createdAt: new Date("2026-02-20"),
  },
  {
    title: "Salmon Avocado Poke Bowl",
    description:
      "Fresh sushi-grade salmon with creamy avocado, edamame, and a tangy sesame-soy dressing.",
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800",
    ingredients: [
      { name: "Sushi-grade Salmon", quantity: "300", unit: "g" },
      { name: "Sushi Rice", quantity: "300", unit: "g" },
      { name: "Avocado", quantity: "2", unit: "pcs" },
      { name: "Edamame", quantity: "150", unit: "g" },
      { name: "Soy Sauce", quantity: "3", unit: "tbsp" },
      { name: "Sesame Oil", quantity: "1", unit: "tbsp" },
      { name: "Sesame Seeds", quantity: "2", unit: "tbsp" },
    ],
    instructions: [
      "Cook sushi rice according to package directions and let cool.",
      "Cube the salmon into bite-sized pieces.",
      "Mix soy sauce and sesame oil for the dressing.",
      "Assemble bowls with rice, salmon, sliced avocado, and edamame.",
      "Drizzle with dressing and garnish with sesame seeds.",
    ],
    tags: ["Asian", "Healthy", "High-Protein", "Gluten-Free", "Lunch"],
    prepTime: 20,
    cookTime: 15,
    servings: 2,
    difficulty: "Easy",
    authorId: "u2",
    authorName: "Mika Tanaka",
    rating: 4.9,
    ratingCount: 89,
    ratingTotal: 436,
    nutritionalInfo: { calories: 480, protein: 35, carbs: 45, fat: 18 },
    createdAt: new Date("2026-02-18"),
  },
  {
    title: "Rustic Sourdough Bread",
    description:
      "Crusty artisanal sourdough with a beautifully open crumb. A 3-day labor of love.",
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800",
    ingredients: [
      { name: "Bread Flour", quantity: "500", unit: "g" },
      { name: "Sourdough Starter", quantity: "100", unit: "g" },
      { name: "Water", quantity: "350", unit: "ml" },
      { name: "Salt", quantity: "10", unit: "g" },
    ],
    instructions: [
      "Mix flour, water, and starter. Autolyse for 30 minutes.",
      "Add salt, fold and stretch every 30 minutes for 3 hours.",
      "Bulk ferment at room temperature for 4-6 hours.",
      "Shape into a boule and cold-proof in fridge for 12-16 hours.",
      "Bake in a Dutch oven at 250°C for 20 min covered, then 20 min uncovered.",
    ],
    tags: ["Vegan", "Breakfast", "Comfort Food"],
    prepTime: 30,
    cookTime: 40,
    servings: 8,
    difficulty: "Hard",
    authorId: "u3",
    authorName: "Marcus Baker",
    rating: 4.7,
    ratingCount: 203,
    ratingTotal: 954,
    nutritionalInfo: { calories: 180, protein: 6, carbs: 36, fat: 1 },
    createdAt: new Date("2026-02-15"),
  },
  {
    title: "Thai Green Curry",
    description:
      "Aromatic coconut curry loaded with vegetables and fresh Thai basil. Comfort in a bowl.",
    image: "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=800",
    ingredients: [
      { name: "Coconut Milk", quantity: "400", unit: "ml" },
      { name: "Green Curry Paste", quantity: "3", unit: "tbsp" },
      { name: "Chicken Thighs", quantity: "500", unit: "g" },
      { name: "Thai Basil", quantity: "1", unit: "bunch" },
      { name: "Fish Sauce", quantity: "2", unit: "tbsp" },
      { name: "Jasmine Rice", quantity: "300", unit: "g" },
      { name: "Lime", quantity: "2", unit: "pcs" },
    ],
    instructions: [
      "Fry curry paste in a splash of coconut milk until fragrant.",
      "Add chicken pieces and sear for 3 minutes.",
      "Pour in remaining coconut milk and simmer for 15 minutes.",
      "Season with fish sauce and lime juice.",
      "Serve over steamed jasmine rice with fresh Thai basil.",
    ],
    tags: ["Asian", "Gluten-Free", "Dinner", "Comfort Food"],
    prepTime: 15,
    cookTime: 25,
    servings: 4,
    difficulty: "Medium",
    authorId: "u4",
    authorName: "Priya Khao",
    rating: 4.6,
    ratingCount: 156,
    ratingTotal: 718,
    nutritionalInfo: { calories: 580, protein: 30, carbs: 42, fat: 28 },
    createdAt: new Date("2026-02-12"),
  },
  {
    title: "Molten Chocolate Lava Cake",
    description:
      "Decadent individual chocolate cakes with a perfectly gooey molten center.",
    image: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=800",
    ingredients: [
      { name: "Dark Chocolate", quantity: "200", unit: "g" },
      { name: "Butter", quantity: "120", unit: "g" },
      { name: "Eggs", quantity: "4", unit: "pcs" },
      { name: "Sugar", quantity: "100", unit: "g" },
      { name: "Flour", quantity: "50", unit: "g" },
      { name: "Raspberries", quantity: "100", unit: "g" },
    ],
    instructions: [
      "Melt chocolate and butter together over a bain-marie.",
      "Whisk eggs and sugar until pale and fluffy.",
      "Fold chocolate mixture into eggs, then gently fold in flour.",
      "Pour into buttered ramekins and bake at 200°C for 12 minutes.",
      "Invert onto plates and serve with fresh raspberries.",
    ],
    tags: ["Dessert", "Vegetarian", "Comfort Food"],
    prepTime: 15,
    cookTime: 12,
    servings: 4,
    difficulty: "Medium",
    authorId: "u5",
    authorName: "Sophie Laurent",
    rating: 4.9,
    ratingCount: 312,
    ratingTotal: 1529,
    nutritionalInfo: { calories: 420, protein: 8, carbs: 38, fat: 28 },
    createdAt: new Date("2026-02-10"),
  },
  {
    title: "Mediterranean Halloumi Salad",
    description:
      "Grilled halloumi on a bed of fresh greens with pomegranate, herbs, and lemon dressing.",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800",
    ingredients: [
      { name: "Halloumi", quantity: "250", unit: "g" },
      { name: "Mixed Greens", quantity: "200", unit: "g" },
      { name: "Pomegranate Seeds", quantity: "100", unit: "g" },
      { name: "Cherry Tomatoes", quantity: "150", unit: "g" },
      { name: "Lemon", quantity: "1", unit: "pc" },
      { name: "Olive Oil", quantity: "3", unit: "tbsp" },
      { name: "Fresh Dill", quantity: "1", unit: "bunch" },
    ],
    instructions: [
      "Slice halloumi into thick pieces and grill until golden.",
      "Toss mixed greens with cherry tomatoes and herbs.",
      "Whisk lemon juice and olive oil for the dressing.",
      "Arrange grilled halloumi over the salad.",
      "Scatter pomegranate seeds and drizzle with dressing.",
    ],
    tags: ["Vegetarian", "Healthy", "Gluten-Free", "Quick", "Lunch"],
    prepTime: 10,
    cookTime: 8,
    servings: 2,
    difficulty: "Easy",
    authorId: "u6",
    authorName: "Elena Papadopoulos",
    rating: 4.5,
    ratingCount: 78,
    ratingTotal: 351,
    nutritionalInfo: { calories: 380, protein: 22, carbs: 18, fat: 24 },
    createdAt: new Date("2026-02-08"),
  },
  {
    title: "Spicy Thai Basil Chicken",
    description:
      "A fragrant stir-fry of chicken with Thai basil, chilies, and savory sauce.",
    image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800",
    ingredients: [
      { name: "Chicken Breast", quantity: "300", unit: "g" },
      { name: "Thai Basil Leaves", quantity: "1", unit: "cup" },
      { name: "Garlic", quantity: "4", unit: "cloves" },
      { name: "Red Chilies", quantity: "2", unit: "pc" },
      { name: "Soy Sauce", quantity: "2", unit: "tbsp" },
      { name: "Oyster Sauce", quantity: "1", unit: "tbsp" },
      { name: "Vegetable Oil", quantity: "2", unit: "tbsp" },
    ],
    instructions: [
      "Heat oil in a wok and sauté garlic and chilies.",
      "Add sliced chicken and cook thoroughly.",
      "Stir in soy and oyster sauce.",
      "Add Thai basil leaves and toss quickly.",
      "Serve hot with steamed rice.",
    ],
    tags: ["Spicy", "Asian", "Dinner", "Quick"],
    prepTime: 10,
    cookTime: 12,
    servings: 2,
    difficulty: "Medium",
    authorId: "u7",
    authorName: "Arjun Mehta",
    rating: 4.7,
    ratingCount: 112,
    ratingTotal: 526,
    nutritionalInfo: { calories: 420, protein: 35, carbs: 12, fat: 24 },
    createdAt: new Date("2026-02-10"),
  },
  {
    title: "Creamy Mushroom Pasta",
    description:
      "Rich and creamy pasta tossed with sautéed mushrooms and parmesan.",
    image: "https://images.unsplash.com/photo-1473093295043-cdd812d0e601?w=800",
    ingredients: [
      { name: "Penne Pasta", quantity: "250", unit: "g" },
      { name: "Mushrooms", quantity: "200", unit: "g" },
      { name: "Heavy Cream", quantity: "200", unit: "ml" },
      { name: "Garlic", quantity: "3", unit: "cloves" },
      { name: "Parmesan Cheese", quantity: "50", unit: "g" },
      { name: "Butter", quantity: "2", unit: "tbsp" },
    ],
    instructions: [
      "Cook pasta until al dente.",
      "Sauté garlic and mushrooms in butter.",
      "Add cream and simmer gently.",
      "Mix in cooked pasta and parmesan.",
      "Serve warm with extra cheese.",
    ],
    tags: ["Vegetarian", "Italian", "Dinner"],
    prepTime: 10,
    cookTime: 15,
    servings: 3,
    difficulty: "Easy",
    authorId: "u8",
    authorName: "Sofia Romano",
    rating: 4.6,
    ratingCount: 95,
    ratingTotal: 437,
    nutritionalInfo: { calories: 520, protein: 16, carbs: 58, fat: 26 },
    createdAt: new Date("2026-02-12"),
  },
  {
    title: "Classic Margherita Pizza",
    description:
      "Traditional Italian pizza topped with fresh mozzarella and basil.",
    image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=800",
    ingredients: [
      { name: "Pizza Dough", quantity: "1", unit: "base" },
      { name: "Tomato Sauce", quantity: "150", unit: "g" },
      { name: "Mozzarella", quantity: "200", unit: "g" },
      { name: "Fresh Basil", quantity: "8", unit: "leaves" },
      { name: "Olive Oil", quantity: "1", unit: "tbsp" },
    ],
    instructions: [
      "Preheat oven to 220°C.",
      "Spread tomato sauce over dough.",
      "Add mozzarella slices evenly.",
      "Bake until crust is golden.",
      "Top with fresh basil and drizzle olive oil.",
    ],
    tags: ["Vegetarian", "Italian", "Lunch"],
    prepTime: 15,
    cookTime: 18,
    servings: 2,
    difficulty: "Medium",
    authorId: "u9",
    authorName: "Luca Bianchi",
    rating: 4.8,
    ratingCount: 140,
    ratingTotal: 672,
    nutritionalInfo: { calories: 610, protein: 22, carbs: 72, fat: 28 },
    createdAt: new Date("2026-02-14"),
  },
  {
    title: "Avocado Chickpea Sandwich",
    description:
      "Healthy mashed chickpeas and avocado layered in whole grain bread.",
    image: "https://images.unsplash.com/photo-1525351484163-7529414344d8?w=800",
    ingredients: [
      { name: "Chickpeas", quantity: "200", unit: "g" },
      { name: "Avocado", quantity: "1", unit: "pc" },
      { name: "Whole Grain Bread", quantity: "4", unit: "slices" },
      { name: "Lemon Juice", quantity: "1", unit: "tbsp" },
      { name: "Black Pepper", quantity: "1", unit: "tsp" },
    ],
    instructions: [
      "Mash chickpeas and avocado together.",
      "Add lemon juice and pepper.",
      "Spread mixture onto bread slices.",
      "Assemble sandwich and cut in halves.",
      "Serve fresh.",
    ],
    tags: ["Vegan", "Healthy", "Breakfast"],
    prepTime: 10,
    cookTime: 0,
    servings: 2,
    difficulty: "Easy",
    authorId: "u10",
    authorName: "Maya Patel",
    rating: 4.4,
    ratingCount: 63,
    ratingTotal: 277,
    nutritionalInfo: { calories: 350, protein: 14, carbs: 40, fat: 15 },
    createdAt: new Date("2026-02-16"),
  },
  {
    title: "Garlic Butter Shrimp Rice",
    description:
      "Juicy shrimp sautéed in garlic butter served over fluffy rice.",
    image: "https://images.unsplash.com/photo-1563379926898-05f4575a45d8?w=800",
    ingredients: [
      { name: "Shrimp", quantity: "300", unit: "g" },
      { name: "Basmati Rice", quantity: "200", unit: "g" },
      { name: "Garlic", quantity: "5", unit: "cloves" },
      { name: "Butter", quantity: "3", unit: "tbsp" },
      { name: "Lemon Juice", quantity: "1", unit: "tbsp" },
      { name: "Parsley", quantity: "2", unit: "tbsp" },
    ],
    instructions: [
      "Cook basmati rice according to package instructions.",
      "Melt butter in a pan and sauté garlic.",
      "Add shrimp and cook until pink and tender.",
      "Stir in lemon juice and chopped parsley.",
      "Serve shrimp over warm rice.",
    ],
    tags: ["Seafood", "Dinner", "Quick"],
    prepTime: 10,
    cookTime: 15,
    servings: 3,
    difficulty: "Medium",
    authorId: "u12",
    authorName: "Carlos Mendes",
    rating: 4.6,
    ratingCount: 88,
    ratingTotal: 405,
    nutritionalInfo: { calories: 480, protein: 32, carbs: 55, fat: 18 },
    createdAt: new Date("2026-02-20"),
  },
  {
    title: "Lemon Herb Grilled Shrimp",
    description:
      "Zesty grilled shrimp marinated in garlic, lemon, and herbs served over fluffy rice.",
    image: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=800",
    ingredients: [
      { name: "Shrimp", quantity: "300", unit: "g" },
      { name: "Basmati Rice", quantity: "200", unit: "g" },
      { name: "Garlic", quantity: "5", unit: "cloves" },
      { name: "Butter", quantity: "3", unit: "tbsp" },
      { name: "Lemon Juice", quantity: "1", unit: "tbsp" },
      { name: "Parsley", quantity: "2", unit: "tbsp" },
    ],
    instructions: [
      "Cook basmati rice according to package instructions.",
      "Melt butter in a pan and sauté garlic.",
      "Add shrimp and cook until pink and tender.",
      "Stir in lemon juice and chopped parsley.",
      "Serve shrimp over warm rice.",
    ],
    tags: ["Seafood", "Dinner", "Quick"],
    prepTime: 10,
    cookTime: 15,
    servings: 3,
    difficulty: "Medium",
    authorId: "u12",
    authorName: "Carlos Mendes",
    rating: 4.6,
    ratingCount: 88,
    ratingTotal: 405,
    nutritionalInfo: { calories: 480, protein: 32, carbs: 55, fat: 18 },
    createdAt: new Date("2026-02-20"),
  },
];

async function seed() {
  try {
    await mongoose.connect(MONGODB_URI);
    console.log("Connected to MongoDB");

    await Recipe.deleteMany({});
    console.log("Cleared existing recipes");

    await Recipe.insertMany(recipes);
    console.log(`Seeded ${recipes.length} recipes`);

    await mongoose.disconnect();
    console.log("Done!");
    process.exit(0);
  } catch (err) {
    console.error("Seed error:", err);
    process.exit(1);
  }
}

seed();
